language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install codecov
  - pip install -r requirements.txt
script:
  - if [ $TRAVIS_BRANCH == 'master' ];
    then py.test --cov-report html --cov pya2l --verbose --cov-fail-under 95;
    else py.test --cov-report html --cov pya2l --verbose;
    fi
  - codecov
