build: false
environment:
  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python37"
      PYTHON_VERSION: "3.7.x"
      PYTHON_ARCH: "32"
install:
  - "%PYTHON%/Scripts/pip.exe install codecov"
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"
test_script:
  - IF "%APPVEYOR_REPO_BRANCH%"=="master" (
    call "%PYTHON%/python.exe" -m pytest --cov-report html --cov pya2l --verbose --cov-fail-under 95
    )
    ELSE
    (
    call "%PYTHON%/python.exe" -m pytest --cov-report html --cov pya2l --verbose
    )
