build: false
environment:
  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
install:
  - "%PYTHON%/Scripts/pip.exe install codecov"
  - "%PYTHON%/Scripts/pip.exe install pytest pytest-cov"
  - "%PYTHON%/Scripts/pip.exe install git+https://github.com/Sauci/pya2l.git@master"
test_script:
  - IF "%APPVEYOR_REPO_BRANCH%"=="master" (
    call "%PYTHON%/python.exe" -m pytest --cov-report html --cov pya2l --verbose --cov-fail-under 95
    )
    ELSE
    (
    call "%PYTHON%/python.exe" -m pytest --cov-report html --cov pya2l --verbose
    )
