build: false
environment:
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.x"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
install:
  - "%PYTHON%/Scripts/pip.exe install codecov"
  - "%PYTHON%/Scripts/pip.exe install pytest pytest-cov"
  - "%PYTHON%/Scripts/pip.exe install git+https://github.com/Sauci/pya2l.git@master"
test_script:
  - "%PYTHON%/Scripts/pytest --cov-report html --cov pya2l --verbose --cov-fail-under 95"
