name: Python package

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build grpcio-tools pytest pytest-cases
          wget https://github.com/Sauci/a2l-grpc/releases/download/v0.1.3/a2l_grpc.tar.gz
          tar -xf a2l_grpc.tar.gz -C pya2l
      - name: Generate gRPC sources
        run: |
          python -m grpc_tools.protoc -I./pya2l/a2l_grpc --python_out=. --pyi_out=. --grpc_python_out=. ./pya2l/a2l_grpc/protobuf/*.proto
      - name: Test with pytest
        run: |
          pytest
      - name: Build distribution
        run: |
          python -m build --sdist --wheel
      - name: Publish package on Python Package Index
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{secrets.PYPI_USERNAME}}
          password: ${{secrets.PYPI_PASSWORD}}
